import 'package:cloud_functions/cloud_functions.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/locale/locale_controller.dart';

/// The full-length PDF report, generated by `generateDetailedReport`.
///
/// BUILT 20 Sep 2026, the client half of the detailed-reports work. See
/// `functions/src/detailedReports.ts` for why every decision about cost and
/// ownership lives on the server.
///
/// ## Why this is a callable and not a direct Vedika request
///
/// Three reasons, all of which would be security or money bugs if the app
/// did this itself:
///
///  - Generating a report **charges the client's prepaid Vedika wallet**. An
///    app-side call is a spend anyone with the APK could trigger in a loop.
///  - Ownership has to be checked against the purchase ledger, which the
///    rules make unreadable-for-write and which a client could otherwise
///    simply lie about.
///  - The idempotency key must be DERIVED from the uid and chart. A
///    client-supplied key could be varied to re-bill the same report forever.
///
/// The app's whole job is to ask, wait, and open the resulting URL.
@immutable
class DetailedReport {
  const DetailedReport({
    required this.reportTitle,
    required this.pageCount,
    required this.sectionCount,
    required this.downloadUrl,
    required this.language,
    required this.cached,
  });

  final String reportTitle;
  final int pageCount;
  final int sectionCount;
  final String downloadUrl;
  final String language;

  /// True when the server returned a previously generated artifact rather
  /// than paying for a new render. Not shown to the user — it exists so the
  /// "this costs money" path stays visible in logs and in tests.
  final bool cached;

  static DetailedReport? fromMap(Map<Object?, Object?>? map) {
    if (map == null) return null;
    final url = map['downloadUrl'];
    if (url is! String || url.isEmpty) return null;
    return DetailedReport(
      reportTitle: map['reportTitle'] is String
          ? map['reportTitle'] as String
          : '',
      pageCount: (map['pageCount'] as num?)?.toInt() ?? 0,
      sectionCount: (map['sectionCount'] as num?)?.toInt() ?? 0,
      downloadUrl: url,
      language: map['language'] is String ? map['language'] as String : 'en',
      cached: map['cached'] == true,
    );
  }
}

/// Why a generation attempt failed, in terms the UI can act on.
enum DetailedReportError {
  /// The purchase ledger says this report was never bought. Not an error the
  /// user can retry past — the UI should send them to the store.
  notPurchased,

  /// Signed out, or the session expired mid-request.
  unauthenticated,

  /// Network, timeout, or Vedika being down. Worth a retry.
  unavailable,

  /// Anything else.
  unknown,
}

class DetailedReportException implements Exception {
  const DetailedReportException(this.error);
  final DetailedReportError error;
}

const String _functionsRegion = 'asia-south1';

class DetailedReportRepository {
  DetailedReportRepository({required this.functions, required this.locale});

  final FirebaseFunctions Function() functions;
  final String locale;

  Future<DetailedReport> generate(String reportId) async {
    try {
      final callable = functions().httpsCallable(
        'generateDetailedReport',
        // Rendering 89 pages takes real time; the SDK's 60s default cut off
        // legitimate responses during testing, and a timeout here is
        // expensive — the server may already have paid for the render.
        options: HttpsCallableOptions(timeout: const Duration(seconds: 180)),
      );
      final result = await callable.call<Map<Object?, Object?>>({
        'reportId': reportId,
        'language': locale,
      });
      final report = DetailedReport.fromMap(result.data);
      if (report == null) {
        throw const DetailedReportException(DetailedReportError.unknown);
      }
      return report;
    } on FirebaseFunctionsException catch (e) {
      throw DetailedReportException(switch (e.code) {
        'permission-denied' => DetailedReportError.notPurchased,
        'unauthenticated' => DetailedReportError.unauthenticated,
        'unavailable' || 'deadline-exceeded' || 'resource-exhausted' =>
          DetailedReportError.unavailable,
        _ => DetailedReportError.unknown,
      });
    } on DetailedReportException {
      rethrow;
    } catch (_) {
      throw const DetailedReportException(DetailedReportError.unavailable);
    }
  }
}

final detailedReportRepositoryProvider = Provider<DetailedReportRepository>((
  ref,
) {
  return DetailedReportRepository(
    functions: () => FirebaseFunctions.instanceFor(region: _functionsRegion),
    // Asked for in the reader's language. The server falls back to English
    // by itself when Vedika has not finished translating that report, so the
    // user still gets the document they paid for rather than an error.
    locale: ref.watch(localeControllerProvider)?.languageCode ?? 'en',
  );
});
